name = "PlotIter"
uuid = "570a651b-f435-48ab-b76d-fb07b459bafb"
authors = ["Tom Gillam <tpgillam@googlemail.com>"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
