name = "PlotIter"
uuid = "570a651b-f435-48ab-b76d-fb07b459bafb"
authors = ["Tom Gillam <tpgillam@googlemail.com>"]
version = "0.2.1"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
julia = "1.6"
Plots = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
